---
# stage = one shared staging box
all:
  children:
    stage:
      children:
        global_stage:
          hosts:
            www-global-stage:
              ansible_host: 10.0.1.20
  vars:
    env: stage
    provider: cloud
    ansible_connection: local
